/* corpora.js — built-in training texts. Shakespeare is public domain; the rest is original. */
(function (root, factory) {
  const mod = factory();
  if (typeof module === 'object' && module.exports) module.exports = mod;
  else root.TV = Object.assign(root.TV || {}, { corpora: mod });
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  // Highly regular text: learns in seconds, attention patterns become crisp
  // (previous-token heads, "copy what came after last time" heads).
  const patterns = (() => {
    const lines = [];
    const words = ['red', 'blue', 'green', 'gold', 'gray', 'pink'];
    for (let i = 0; i < 30; i++) {
      const a = words[i % 6], b = words[(i * 5 + 1) % 6];
      lines.push(`${a} ${b} ${a} ${b} ${a} ${b}.`);
      lines.push(`1 2 3 4 5 6 7 8 9.`);
      lines.push(`abc abc abd abd abe abe.`);
    }
    return lines.join('\n') + '\n';
  })();

  const shakespeare = `Shall I compare thee to a summer's day?
Thou art more lovely and more temperate:
Rough winds do shake the darling buds of May,
And summer's lease hath all too short a date;
Sometime too hot the eye of heaven shines,
And often is his gold complexion dimm'd;
And every fair from fair sometime declines,
By chance or nature's changing course untrimm'd;
But thy eternal summer shall not fade,
Nor lose possession of that fair thou ow'st;
Nor shall death brag thou wander'st in his shade,
When in eternal lines to time thou grow'st:
So long as men can breathe or eyes can see,
So long lives this, and this gives life to thee.

Let me not to the marriage of true minds
Admit impediments. Love is not love
Which alters when it alteration finds,
Or bends with the remover to remove.
O no! it is an ever-fixed mark
That looks on tempests and is never shaken;
It is the star to every wand'ring bark,
Whose worth's unknown, although his height be taken.
Love's not Time's fool, though rosy lips and cheeks
Within his bending sickle's compass come;
Love alters not with his brief hours and weeks,
But bears it out even to the edge of doom.
If this be error and upon me prov'd,
I never writ, nor no man ever lov'd.

My mistress' eyes are nothing like the sun;
Coral is far more red than her lips' red;
If snow be white, why then her breasts are dun;
If hairs be wires, black wires grow on her head.
I have seen roses damask'd, red and white,
But no such roses see I in her cheeks;
And in some perfumes is there more delight
Than in the breath that from my mistress reeks.
I love to hear her speak, yet well I know
That music hath a far more pleasing sound;
I grant I never saw a goddess go;
My mistress, when she walks, treads on the ground:
And yet, by heaven, I think my love as rare
As any she belied with false compare.

When, in disgrace with fortune and men's eyes,
I all alone beweep my outcast state,
And trouble deaf heaven with my bootless cries,
And look upon myself and curse my fate,
Wishing me like to one more rich in hope,
Featur'd like him, like him with friends possess'd,
Desiring this man's art and that man's scope,
With what I most enjoy contented least;
Yet in these thoughts myself almost despising,
Haply I think on thee, and then my state,
Like to the lark at break of day arising
From sullen earth, sings hymns at heaven's gate;
For thy sweet love remember'd such wealth brings
That then I scorn to change my state with kings.
`;

  const refinery = `The crude unit heats the feed in the furnace and sends it to the atmospheric column.
The atmospheric column splits the crude into gas, naphtha, kerosene, diesel and residue.
The residue goes to the vacuum column, where lower pressure lets heavy oil boil at a lower temperature.
The vacuum gas oil feeds the cracker. The vacuum residue goes to the coker or to fuel oil.
The cracker breaks heavy molecules into lighter ones on a hot catalyst.
The catalyst is regenerated by burning off the coke in the regenerator.
The reformer raises the octane of the naphtha and makes hydrogen as a by-product.
The hydrotreater uses that hydrogen to remove sulfur from diesel and kerosene.
When the furnace outlet temperature rises, the operator cuts the firing.
When the column pressure rises, the operator checks the overhead condenser.
When the reflux drum level rises, the operator increases the reflux or the product draw.
When the bottoms level falls, the operator reduces the bottoms draw.
If the pump trips, the operator starts the spare pump and checks the suction pressure.
If the flare is lit, the operator checks the relief valves and the column pressure.
The controller compares the process value with the set point and moves the valve.
A good controller is tuned so that the process value settles quickly without oscillation.
Too much gain makes the loop oscillate. Too little gain makes the loop slow.
The heat balance and the mass balance must close before the model can be trusted.
Fouling in the exchanger lowers the heat transfer and raises the furnace duty.
Every shift the operator logs the flows, the temperatures, the pressures and the levels.
`;

  return {
    list: [
      { id: 'patterns', name: 'Patterns (learns fast)', text: patterns },
      { id: 'refinery', name: 'Refinery operations', text: refinery },
      { id: 'shakespeare', name: 'Shakespeare sonnets', text: shakespeare },
      { id: 'custom', name: 'Custom text…', text: '' },
    ],
    MAX_CUSTOM_CHARS: 50000,
  };
});
